### PR TITLE
Add OffsetArrays as a test requirement

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by tkelman** [comment]
really strange that travis is running on pr's but not branches

**Comment by timholy** [comment]
Looks like "Build pushes" is off on the travis settings page. I'm tempted to leave it that way, as I'm not sure the duplication is really worth it.

**Comment by timholy** [comment]
Hmm, the badge wasn't updating, perhaps merges to master weren't being run either. So I flipped that on, we'll see if that fixes it next time this gets updated.

**Comment by tkelman** [comment]
yeah master is counted as a branch - but you can set `branches: only` to avoid the double builds on PR's

**Pull request merged**
